export const MANGO_DATA_API_URL = 'https://api.mngo.cloud/data/v4'

export const CUSTOM_TOKEN_ICONS: { [key: string]: boolean } = {
  all: true,
  blze: true,
  bome: true,
  bonk: true,
  bsol: true,
  btc: true,
  chai: true,
  corn: true,
  crown: true,
  dai: true,
  dual: true,
  elon: true,
  eth: true,
  ethpo: true,
  'eth (portal)': true,
  eurc: true,
  gecko: true,
  gofx: true,
  guac: true,
  hnt: true,
  inf: true,
  jitosol: true,
  jlp: true,
  jsol: true,
  jto: true,
  jup: true,
  kin: true,
  kmno: true,
  ldo: true,
  meta: true,
  mew: true,
  mnde: true,
  mngo: true,
  moutai: true,
  msol: true,
  neon: true,
  nos: true,
  opos: true,
  orca: true,
  popcat: true,
  pups: true,
  pyth: true,
  ray: true,
  render: true,
  rlb: true,
  samo: true,
  slcl: true,
  slerf: true,
  sol: true,
  step: true,
  stsol: true,
  tbtc: true,
  tnsr: true,
  usdc: true,
  usdh: true,
  usdt: true,
  w: true,
  wbtcpo: true,
  'wbtc (portal)': true,
  wen: true,
  wif: true,
  $wif: true,
  zeus: true,
}

export const DAILY_SECONDS = 86400
export const DAILY_MILLISECONDS = 86400000

export const MAX_CONTENT_WIDTH = 'max-w-[1280px]'

export const ARTICLE_LIMIT = 3
