export const MANGO_DATA_API_URL = 'https://api.mngo.cloud/data/v4'

export const CUSTOM_TOKEN_ICONS: { [key: string]: boolean } = {
  all: true,
  bonk: true,
  bsol: true,
  btc: true,
  chai: true,
  crown: true,
  dai: true,
  dual: true,
  eth: true,
  ethpo: true,
  'eth (portal)': true,
  guac: true,
  hnt: true,
  jitosol: true,
  jlp: true,
  jto: true,
  kin: true,
  ldo: true,
  mngo: true,
  msol: true,
  neon: true,
  orca: true,
  pyth: true,
  ray: true,
  render: true,
  rlb: true,
  slcl: true,
  sol: true,
  stsol: true,
  tbtc: true,
  usdc: true,
  usdh: true,
  usdt: true,
  wbtcpo: true,
  'wbtc (portal)': true,
}

export const DAILY_SECONDS = 86400
export const DAILY_MILLISECONDS = 86400000
